apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-k6rz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-k6rz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-k6rz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-k6rz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-k6rz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dcmy-tenant/rhtap-demo-app/hacbs-test-project-k6rz@sha256:a52d61d186c666059951c80a68cf3e357985bcb3edd640c1fdd9ca013f45f6ef
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
